AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Evolvex Auth backend using AWS SAM and Node.js 18

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 15
    MemorySize: 512
    AutoPublishAlias: live
    Tracing: Active
    CodeUri: .
    Environment:
      Variables:
        JWT_SECRET: !Ref JWTSecret
        JWT_EXPIRES: !Ref JWTExpires

  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH'"
      AllowHeaders: "'Content-Type,Authorization,X-Requested-With'"
      AllowOrigin: "'*'"

Parameters:
  JWTSecret:
    Type: String
  JWTExpires:
    Type: String

Resources:
  EvolvexApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,GET,PUT,POST,DELETE,PATCH'"
        AllowHeaders: "'Content-Type,Authorization,X-Requested-With'"
        AllowOrigin: "'*'"

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function/AuthRoute/app.handler
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: POST
            RestApiId: !Ref EvolvexApi

        LoginAlias:
          Type: Api
          Properties:
            Path: /auth/login
            Method: POST
            RestApiId: !Ref EvolvexApi

        Verify:
          Type: Api
          Properties:
            Path: /auth/verify
            Method: GET
            RestApiId: !Ref EvolvexApi

  SubscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: function/SubscriptionRoute/app.handler
      Events:
        PaymentHistory:
          Type: Api
          Properties:
            Path: /subscriptions/payment-history
            Method: GET
            RestApiId: !Ref EvolvexApi

        PaymentHistoryAlias:
          Type: Api
          Properties:
            Path: /api/subscriptions/payment-history
            Method: GET
            RestApiId: !Ref EvolvexApi

        CurrentSubscription:
          Type: Api
          Properties:
            Path: /subscriptions/current
            Method: GET
            RestApiId: !Ref EvolvexApi

        CurrentSubscriptionAlias:
          Type: Api
          Properties:
            Path: /api/subscriptions/current
            Method: GET
            RestApiId: !Ref EvolvexApi

Outputs:
  ApiUrl:
    Description: Evolvex Auth API base URL
    Value: !Sub "https://${EvolvexApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
